version: '2'

volumes:
  records:
    driver_opts:
      type: none
      device: $PWD/data/
      o: bind

services:
  rtmp:
    container_name: rtmp
    image: lasery/watchdog:rtmp
    volumes:
      - records:/root/picam/archive/
    privileged: true
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
      - "1936:1936"
    environment:
      - TZ=Asia/Hong_Kong
      - CONVERT_VIDEO=true
      - DEBUG_MODE=false
    privileged: true
    command: /root/app/convert.sh
    restart: unless-stopped

  picam:
    container_name: picam
    image: lasery/watchdog:picam
    volumes:
      - records:/home/picam/archive/
    privileged: true
    environment:
      - TZ=Asia/Hong_Kong
    command: >
      /bin/bash -c "
        echo testing rtmp connection;
        while ! nc -z rtmp 1936;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
        /docker-entrypoint.sh start --noaudio --time --videobitrate 500000 --fps 10 --tcpout tcp://rtmp:8181
      "
    depends_on:
      - rtmp
    restart: unless-stopped

  frp-server:
    container_name: frp-server
    image: lasery/frp
    volumes:
      - ./frp/frps.ini:/root/frp/frps.ini
    entrypoint: /root/frp/frps
    command: -c /root/frp/frps.ini
    ports:
      - "7000:7000"
      - "10022:22"
      - "1935:1935"
      - "1936:1936"
    restart: unless-stopped

  frp-client:
    container_name: frp-client
    image: lasery/frp:pizero
    volumes:
      - ./frp/frpc.ini:/root/frp/frpc.ini
    entrypoint: /root/frp/frpc
    command: -c /root/frp/frpc.ini
    restart: unless-stopped
