version: '2'

services:
  busybox:
    image: hypriot/armhf-busybox
    command: tail -f /dev/null
    # volumes_from:
      # - picam
      # - rtmp
  rtmp:
    build: ./rtmp/

  picam:
    build: ./picam/

  frp-server:
    build: ./frp/

  frp-client:
    build: ./frp/
