version: '2'

services:
  busybox:
    image: hypriot/armhf-busybox
    command: tail -f /dev/null

  rtmp:
    # image: watchdog:rtmp
    volumes:
      # - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
      - ./rtmp/app/:/root/app/
    # environment:
      # - CONVERT_VIDEO=false
      # - DEBUG_MODE=true
    restart: "no"

  picam:
    # image: watchdog:picam
    # volumes:
      # - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
      # - ./picam/hooks.sh:/home/picam/hooks.sh
    # command: >
      # /bin/bash -c "
        # echo testing rtmp connection;
        # while ! nc -z rtmp 1936;
        # do
          # echo sleeping;
          # sleep 1;
        # done;
        # echo Connected!;
        # /docker-entrypoint.sh start --noaudio --time --width 630 --height 270 --videobitrate 200000 --fps 15 --tcpout tcp://rtmp:8181
      # "

    # command: start --noaudio --time --videobitrate 500000 --fps 10 --tcpout tcp://rtmp:8181
    # command: start --alsadev hw:1,0 --time --width 630 --height 270 --videobitrate 200000 --fps 15 --tcpout tcp://rtmp:8181
    restart: "no"

  frp-server:

  frp-client:

  dev-cli:
    image: tianon/true
    restart: "no"
    depends_on:
      - picam
      - rtmp
