version: '2'

services:
  picam:
    command: >
      /bin/bash -c "
        echo testing rtmp connection;
        while ! nc -z rtmp 8181;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
        sleep 10 `# wait rtmp-ffmpeg restart from connection test`;
        /docker-entrypoint.sh start --verbose --noaudio --time --videobitrate 500000 --fps 10 --tcpout tcp://rtmp:8181
      "
