version: '2'

services:
  rtmp:
    image: lasery/nginx-rtmp:pizero
    volumes:
      - ./rtmp/nginx.conf:/usr/local/nginx/conf/nginx.conf
    volumes_from:
      - picam
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    command: /usr/local/nginx/sbin/nginx -g 'daemon off;'
    restart: always

  picam:
    image: lasery/picam:pizero
    volumes:
      - /root/picam/archive/
      - ./picam/record.sh:/record.sh
    privileged: true
    environment:
      - TZ=Asia/Hong_Kong
    # command: ./picam --time --width 640 --height 480 --videobitrate 500000 --fps 20 --noaudio --tcpout tcp://rtmp:8181
    command: /record.sh
    restart: always

  frp-server:
    image: lasery/frp
    volumes:
      - ./frp/frps.ini:/root/frp/frps.ini
    entrypoint: /root/frp/frps
    command: -c /root/frp/frps.ini
    ports:
      - "7000:7000"
      - "10022:22"
      - "1935:1935"
      - "80:80"
    restart: always

  frp-client:
    image: lasery/frp:pizero
    volumes:
      - ./frp/frpc.ini:/root/frp/frpc.ini
    entrypoint: /root/frp/frpc
    command: -c /root/frp/frpc.ini
    restart: always

  prod-cli:
    image: tianon/true
    restart: "no"
    depends_on:
      - frp-client
      - picam
      - rtmp
