version: '2'

services:
  rtmp:
    image: lasery/nginx-rtmp:pizero
    volumes:
      - ./rtmp/nginx.conf:/usr/local/nginx/conf/nginx.conf
    volumes_from:
      - picam
    ports:
      - "80:80"
      - "443:443"
    entrypoint: /usr/local/nginx/sbin/nginx
    command: -g 'daemon off;'
    restart: always

  picam:
    image: lasery/picam:pizero
    volumes:
      - /root/picam/rec/
    privileged: true
    command: ./picam --noaudio
    # command: ./picam --alsadev hw:1,0
    restart: always

  frp-server:
    image: lasery/frp
    volumes:
      - ./frp/frps.ini:/root/frp/frps.ini
    entrypoint: /root/frp/frps
    command: -c /root/frp/frps.ini
    ports:
      - "7000:7000"
      - "10022:22"

  frp-client:
    image: lasery/frp:pizero
    volumes:
      - ./frp/frpc.ini:/root/frp/frpc.ini
    entrypoint: /root/frp/frpc
    command: -c /root/frp/frpc.ini
    restart: always

  home-care:
    image: tianon/true
    restart: "no"
    depends_on:
      - frp-client
