version: '2'

services:
  busybox:
    image: hypriot/armhf-busybox
    command: tail -f /dev/null
    # volumes_from:
      # - picam
      # - rtmp
  rtmp:
    image: watchdog:rtmp
    volumes:
      - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static

  picam:

  frp-server:

  frp-client:

  dev-cli:
    image: tianon/true
    restart: "no"
    depends_on:
      - picam
      - rtmp
