version: '2'

services:
  rtmp:
    image: lasery/watchdog:rtmp

  picam:
    image: lasery/watchdog:picam

  frp-server:

  frp-client:

  dev-cli:
    image: tianon/true
    restart: "no"
    depends_on:
      - picam
      - rtmp

  prod-cli:
    image: tianon/true
    restart: "no"
    depends_on:
      - frp-client
      - picam
      - rtmp
