version: '2'

services:
  busybox:
    image: hypriot/armhf-busybox
    command: tail -f /dev/null

  rtmp:
    image: lasery/watchdog:rtmp

  picam:
    image: lasery/watchdog:picam

  frp-server:

  frp-client:

  dev-cli:
    image: tianon/true
    restart: "no"
    depends_on:
      - picam
      - rtmp
