version: '2'

volumes:
  records:
    driver_opts:
      type: none
      device: $PWD/data/
      o: bind

services:
  rtmp:
    container_name: rtmp
    image: lasery/nginx-rtmp:pizero
    volumes:
      - records:/root/picam/archive/
      - ./rtmp/app/:/root/app/
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
      - "1936:1936"
    # command: /usr/local/nginx/sbin/nginx -g 'daemon off;'
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
      - TZ=Asia/Hong_Kong
    privileged: true
    devices:
      - "/dev/vchiq:/dev/vchiq"
    command: /root/app/convert.sh
    restart: always

  picam:
    container_name: picam
    image: lasery/picam:pizero
    volumes:
      - records:/root/picam/archive/
      - ./picam/record.sh:/record.sh
    privileged: true
    environment:
      - TZ=Asia/Hong_Kong
    # command: ./picam --time --width 640 --height 480 --videobitrate 500000 --fps 20 --noaudio --tcpout tcp://rtmp:8181
    depends_on:
      - rtmp
    command: /record.sh
    restart: always

  frp-server:
    container_name: frp-server
    image: lasery/frp
    volumes:
      - ./frp/frps.ini:/root/frp/frps.ini
    entrypoint: /root/frp/frps
    command: -c /root/frp/frps.ini
    ports:
      - "7000:7000"
      - "10022:22"
      - "1935:1935"
      - "1936:1936"
    restart: always

  frp-client:
    container_name: frp-client
    image: lasery/frp:pizero
    volumes:
      - ./frp/frpc.ini:/root/frp/frpc.ini
    entrypoint: /root/frp/frpc
    command: -c /root/frp/frpc.ini
    restart: always

  prod-cli:
    image: tianon/true
    restart: "no"
    depends_on:
      - frp-client
      - picam
      - rtmp
