version: '2'

volumes:
  records:
    driver_opts:
      type: none
      device: $PWD/data/
      o: bind

services:
  rtmp:
    container_name: rtmp
    image: watchdog:rtmp
    volumes:
      - records:/root/picam/archive/
      - ./rtmp/app/:/root/app/
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
      - "1936:1936"
    environment:
      - TZ=Asia/Hong_Kong
    privileged: true
    command: /root/app/convert.sh
    restart: unless-stopped

  picam:
    container_name: picam
    image: lasery/picam
    volumes:
      - records:/home/picam/archive/
      - ./picam:/home/picam/app/
    privileged: true
    environment:
      - TZ=Asia/Hong_Kong
    command: /home/picam/app/record.sh
    depends_on:
      - rtmp
    restart: unless-stopped

  frp-server:
    container_name: frp-server
    image: lasery/frp
    volumes:
      - ./frp/frps.ini:/root/frp/frps.ini
    entrypoint: /root/frp/frps
    command: -c /root/frp/frps.ini
    ports:
      - "7000:7000"
      - "10022:22"
      - "1935:1935"
      - "1936:1936"
    restart: unless-stopped

  frp-client:
    container_name: frp-client
    image: lasery/frp:pizero
    volumes:
      - ./frp/frpc.ini:/root/frp/frpc.ini
    entrypoint: /root/frp/frpc
    command: -c /root/frp/frpc.ini
    restart: unless-stopped

  prod-cli:
    image: tianon/true
    restart: "no"
    depends_on:
      - frp-client
      - picam
      - rtmp
